# Generated by Django 5.0.1 on 2026-01-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_dividend_historicalprice_stock_stocksplit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Unique username for the new user', max_length=150, verbose_name='Username')),
                ('email', models.EmailField(help_text='Email address of the applicant', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(help_text='First name of the applicant', max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last name of the applicant', max_length=150, verbose_name='Last Name')),
                ('password_hash', models.CharField(blank=True, help_text="Hash of the user's password", max_length=128, null=True, verbose_name='Password Hash')),
                ('registration_type', models.CharField(choices=[('manual', 'Manual Registration'), ('google', 'Google Registration')], default='manual', help_text='Method used for registration', max_length=20, verbose_name='Registration Type')),
                ('google_id', models.CharField(blank=True, help_text="User's unique Google ID", max_length=255, null=True, verbose_name='Google ID')),
                ('google_picture', models.URLField(blank=True, help_text='URL of the Google profile picture', null=True, verbose_name='Google Picture')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the request', max_length=20, verbose_name='Status')),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date and time of the request', verbose_name='Request Date')),
                ('processed_date', models.DateTimeField(blank=True, help_text='Date and time of approval/rejection', null=True, verbose_name='Processed Date')),
                ('notes', models.TextField(blank=True, help_text='Additional administrator notes', verbose_name='Notes')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Administrator who processed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Registration Request',
                'verbose_name_plural': 'Registration Requests',
                'ordering': ['-request_date'],
            },
        ),
    ]
