# Generated by Django 5.0.1 on 2026-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_financialmetrics_fcf_payout_ratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_symbol', models.CharField(db_index=True, help_text="Old or alternative symbol (e.g., 'FB', 'TWTR')", max_length=10, unique=True)),
                ('new_symbol', models.CharField(db_index=True, help_text="Current symbol to redirect to (e.g., 'META', 'X')", max_length=10)),
                ('reason', models.CharField(blank=True, help_text="Reason for redirect (e.g., 'Rebranded from Facebook to Meta')", max_length=200)),
                ('exchange_hint', models.CharField(blank=True, help_text="Preferred exchange (e.g., 'NASDAQ', 'NYSE')", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if redirect is no longer valid')),
            ],
            options={
                'verbose_name': 'Symbol Redirect',
                'verbose_name_plural': 'Symbol Redirects',
                'ordering': ['old_symbol'],
                'indexes': [models.Index(fields=['old_symbol', 'is_active'], name='research_sy_old_sym_8a1f37_idx'), models.Index(fields=['new_symbol'], name='research_sy_new_sym_d4f9c4_idx')],
            },
        ),
    ]
