# Generated by Django 5.0.1 on 2026-02-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broker',
            field=models.CharField(blank=True, help_text="Broker used for this transaction (e.g., 'Robinhood', 'Fidelity')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buy_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dividend yield at time of purchase (as percentage)', max_digits=5, null=True),
        ),
    ]
