# Generated by Django 5.0.1 on 2026-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_transaction_broker_transaction_buy_yield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIV', 'Dividend'), ('SPOF', 'Spin-Off'), ('INT', 'Interest')], max_length=8),
        ),
    ]
