# Generated by Django 5.0.1 on 2026-06-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_currency_transaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
