# Generated by Django 5.0.1 on 2026-06-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_dividend_payment_date_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
