# Generated by Django 5.0.1 on 2026-06-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_dividend_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='native_currency',
            field=models.CharField(choices=[('EUR', 'Euro (EUR)'), ('USD', 'US Dollar (USD)'), ('GBP', 'British Pound (GBP)'), ('CHF', 'Swiss Franc (CHF)'), ('JPY', 'Japanese Yen (JPY)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('SEK', 'Swedish Krona (SEK)'), ('NOK', 'Norwegian Krone (NOK)'), ('DKK', 'Danish Krone (DKK)')], default='EUR', help_text='Tax reporting currency for this portfolio', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_currency',
            field=models.CharField(blank=True, help_text='Currency the commission is denominated in (EXC transactions)', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='1 transaction_currency = fx_rate native_currency, on transaction date', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_rate_source',
            field=models.CharField(blank=True, help_text="'frankfurter' or 'manual'", max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='native_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total transaction amount converted to portfolio native currency', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency of this transaction (e.g. USD for a US stock)', max_length=10),
        ),
        migrations.CreateModel(
            name='FXLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Foreign currency this lot is denominated in', max_length=10)),
                ('lot_type', models.CharField(choices=[('REAL', 'Real Exchange'), ('VIRTUAL_SELL', 'Virtual — Stock Sale'), ('VIRTUAL_DIV', 'Virtual — Dividend'), ('VIRTUAL_INT', 'Virtual — Interest')], max_length=20)),
                ('created_date', models.DateField()),
                ('original_amount_foreign', models.DecimalField(decimal_places=4, max_digits=15)),
                ('remaining_amount_foreign', models.DecimalField(decimal_places=4, max_digits=15)),
                ('fx_rate', models.DecimalField(decimal_places=8, help_text='1 foreign currency unit = fx_rate native currency units at lot creation', max_digits=18)),
                ('original_amount_native', models.DecimalField(decimal_places=4, max_digits=15)),
                ('is_closed', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_lots', to='portfolio.portfolio')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_lots', to='portfolio.transaction')),
            ],
            options={
                'ordering': ['created_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FXLotConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_foreign_consumed', models.DecimalField(decimal_places=4, max_digits=15)),
                ('fx_rate_at_consumption', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fx_gain_loss_native', models.DecimalField(decimal_places=4, help_text='Positive = FX gain, negative = FX loss, in native currency', max_digits=15)),
                ('consumption_date', models.DateField()),
                ('consuming_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_lot_consumptions', to='portfolio.transaction')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='portfolio.fxlot')),
            ],
            options={
                'ordering': ['consumption_date', 'id'],
            },
        ),
    ]
